version: "3"

x-service: &service
  restart: unless-stopped

services:

  minio:
    <<: *service
    image: quay.io/minio/minio:RELEASE.2024-06-06T09-36-42Z-cpuv1
    command: server /data --address ":9000" --console-address ":9001"
    container_name: minio
    volumes:
      - minio:/data
    environment:
      - MINIO_ROOT_USER=${FSSPEC_S3_KEY}
      - MINIO_ROOT_PASSWORD=${FSSPEC_S3_SECRET}
    ports:
      - "9001:9001"
      - "9000:9000"

  postgres:
    <<: *service
    image: postgres:16.3-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: leaders2024
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  minio:
  postgres:
  llama-volume: